from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import httpx


@dataclass(frozen=True)
class GithubAdapter:
    api_base: str = "https://api.github.com"

    async def post_finding_issue(self, finding: dict[str, Any], repo: str, token: str) -> str:
        url = f"{self.api_base.rstrip('/')}/repos/{repo}/issues"
        response: httpx.Response
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(
                url,
                headers=self._auth_headers(token),
                json={
                    "title": self._issue_title(finding),
                    "body": self.format_evidence_summary(finding),
                    "labels": [finding.get("safety_label") or "security"],
                },
            )
        response.raise_for_status()
        payload = response.json()
        return str(payload.get("html_url") or payload["url"])

    def format_evidence_summary(self, finding: dict[str, Any]) -> str:
        lines = [
            "# Security finding",
            "",
            f"- **Severity:** {self._field(finding, 'severity')}",
            f"- **Attack class:** {self._field(finding, 'attack_class')}",
            f"- **Safety label:** {self._field(finding, 'safety_label')}",
        ]

        team = finding.get("owner_team")
        service = finding.get("owner_service")
        if team:
            lines.append(f"- **Owner team:** {team}")
        if service:
            lines.append(f"- **Owner service:** {service}")

        lines.extend(
            [
                "",
                "## Evidence",
                self._block_value(finding.get("evidence_summary")),
                "",
                "## Reproduction steps",
                self._block_value(finding.get("repro_steps")),
                "",
                "## Fix guidance",
                self._block_value(finding.get("fix_guidance")),
            ]
        )
        return "\n".join(lines)

    def format_pr_scan_summary(
        self,
        scan_id: str,
        target_url: str,
        api_url: str,
        new_findings: list[dict[str, Any]],
        fixed_count: int,
        unchanged_count: int,
    ) -> str:
        """PR comment body: proof summary, owner, replay command, suppress info."""
        sections = [
            "## BreachForge Security Scan Results",
            "",
            f"**Scan ID:** `{scan_id}`  **Target:** `{target_url}`",
            "",
            "| Status | Count |",
            "|--------|-------|",
            f"| 🔴 New findings | {len(new_findings)} |",
            f"| ✅ Fixed | {fixed_count} |",
            f"| ➡️ Unchanged | {unchanged_count} |",
            "",
        ]
        if new_findings:
            sections.append("### New Findings")
            for finding in new_findings:
                severity = self._field(finding, "severity")
                attack_class = self._field(finding, "attack_class")
                owner = finding.get("owner_team") or finding.get("owner_service") or "unassigned"
                confidence = finding.get("confidence_score", "n/a")
                endpoint = self._field(finding, "target_url")
                replay_cmd = f"breachforge scan run --target {endpoint}"
                suppress_url = f"{api_url.rstrip('/')}/api/findings/{finding.get('id', '?')}/suppress"
                sections += [
                    f"#### [{severity}] {attack_class}",
                    f"- **Owner:** {owner}",
                    f"- **Confidence:** {confidence}",
                    f"- **Replay:** `{replay_cmd}`",
                    f"- **Suppress:** {suppress_url}",
                    "",
                ]
        else:
            sections.append("_No new security findings. Gates passed._")
        sections += ["", "---", "_Generated by [BreachForge](https://breachforge.io)_"]
        return "\n".join(sections)

    async def add_pr_comment(self, pr_number: int, body: str, repo: str, token: str) -> None:
        url = f"{self.api_base.rstrip('/')}/repos/{repo}/issues/{pr_number}/comments"
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(url, headers=self._auth_headers(token), json={"body": body})
        response.raise_for_status()

    def _auth_headers(self, token: str) -> dict[str, str]:
        return {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
        }

    def _issue_title(self, finding: dict[str, Any]) -> str:
        severity = self._field(finding, "severity")
        attack_class = self._field(finding, "attack_class")
        return f"[{severity}] {attack_class} security finding"

    def _field(self, finding: dict[str, Any], key: str) -> str:
        value = finding.get(key)
        if value in (None, ""):
            return "unknown"
        return str(value)

    def _block_value(self, value: Any) -> str:
        if value in (None, ""):
            return "Not provided."
        if isinstance(value, list):
            return "\n".join(f"{index}. {item}" for index, item in enumerate(value, start=1))
        return str(value)
